import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const task=await taskSpace(Number(process.env.EGO_TASK_SPACE||11));const page=task.page('p1');const cases=[];
await page.goto((process.env.BOOKSTORE_WEB_BASE||'http://127.0.0.1:5173')+'/policies');await page.waitForFunction(()=>document.querySelector('.policy-full summary'),undefined,{timeout:20000});console.log(await page.snapshot());
const initial=await page.evaluate(()=>({heading:document.querySelector('h1').textContent,note:document.querySelector('.policy-note').textContent,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(initial.overflow,false);assert.match(initial.note,/课程演示/);cases.push({case:'welcome',...initial});
await page.fill('#policy-question','拆了包装，但不喜欢这本书，能退吗？');await page.click('.policy-search-row button');await page.waitForSelector('.policy-clause',{timeout:30000});const opened=await page.evaluate(()=>document.querySelector('.policy-results').textContent);assert.match(opened,/不接受非质量原因退货/);assert.match(opened,/质量问题/);cases.push({case:'opened-book-policy',text:opened});
await page.fill('#policy-question','今天月球天气如何');await page.click('.policy-search-row button');await page.waitForFunction(()=>document.querySelector('.policy-result-label')?.textContent.includes('暂无'),undefined,{timeout:30000});cases.push({case:'unrelated-abstain',text:await page.evaluate(()=>document.querySelector('.policy-results').textContent)});
await page.evaluate(()=>document.querySelector('.policy-full').scrollIntoView({block:'center'}));await page.click('.policy-full summary');assert.equal(await page.evaluate(()=>document.querySelectorAll('.policy-full-body h3').length),6);cases.push({case:'full-policy',sections:6});
await page.cdp('Network.enable');
try{await page.cdp('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1});await page.fill('#policy-question','会员怎么攒积分');await page.click('.policy-search-row button');await page.waitForSelector('.policy-results .ant-alert-error',{timeout:10000});cases.push({case:'offline-error',text:await page.evaluate(()=>document.querySelector('.policy-results').textContent)});}
finally{await page.cdp('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});}
await page.click('.policy-results .ant-alert button');await page.waitForSelector('.policy-clause',{timeout:30000});const member=await page.evaluate(()=>document.querySelector('.policy-results').textContent);assert.match(member,/每满1元积1分/);cases.push({case:'retry-member',text:member});
await page.evaluate(()=>window.scrollTo(0,210));
await fs.writeFile(new URL('../../docs/assignments/evidence/3a-browser.json',import.meta.url),JSON.stringify({testedAt:new Date().toISOString(),cases,functionalComplete:true,visualReview:{complete:false},complete:false},null,2)+'\n');console.log('真实政策页面欢迎、拆封条件、无依据、全文、断网与重试通过。');
