import fs from 'node:fs/promises';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {chunkPolicy} from '../../embedding-service/chunks.mjs';
const api=process.env.BOOKSTORE_API_BASE||'http://127.0.0.1:8080';const embeddings=process.env.EMBEDDING_BASE||'http://127.0.0.1:8091';
const text=await fs.readFile(new URL('../../backend/src/main/resources/store-policy.txt',import.meta.url),'utf8');const chunks=chunkPolicy(text);assert.equal(chunks.length,6);const sectionBodies=text.split(/^## .+\n/gm).slice(1).map(s=>s.trim());assert.deepEqual(chunks.map(c=>c.text),sectionBodies);assert.throws(()=>chunkPolicy('## 长条款\n'+'字'.repeat(421)));assert.throws(()=>chunkPolicy('无标题文档'));
const diagnostics=await(await fetch(embeddings+'/diagnostics')).json();assert.equal(diagnostics.dimension,512);assert.equal(diagnostics.sourceHash,crypto.createHash('sha256').update(text).digest('hex'));assert.equal(diagnostics.vectors.length,6);for(const v of diagnostics.vectors){assert.equal(v.vector.length,512);assert.ok(v.vector.every(Number.isFinite));assert.ok(Math.abs(Math.hypot(...v.vector)-1)<0.002);}
const cases=[['包装膜拆开后，因为不好看想退书',2],['到货发现缺了几页，但我已经打开包装了',3],['积分有效期多久，消费怎么攒积分',5],['收到书四天，保持包装完好，买重了能退吗',1],['审核通过寄回之后钱什么时候退',4],['今天月球天气如何',null]];
const results=[];
for(const [query,expected] of cases){const response=await fetch(api+'/api/policies/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const body=await response.json();assert.equal(response.status,200);const r=body.data;results.push({query,expected,response:r});await fs.writeFile(new URL('../../docs/assignments/evidence/3a-real-rag.json',import.meta.url),JSON.stringify({results,complete:false},null,2)+'\n');if(expected)assert.ok(r.chunks.some(c=>c.id==='policy-'+expected));else assert.equal(r.matched,false);}
for(const query of [' ','字'.repeat(601)]){const r=await fetch(api+'/api/policies/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});assert.equal(r.status,400);}
const document=await(await fetch(api+'/api/policies/document')).json();assert.equal(document.data.chunks.length,6);assert.equal(document.data.text,text);
const evidence={testedAt:new Date().toISOString(),environment:'真实本机q8中文模型、512维向量及Spring HTTP，无模拟向量',diagnostics,results,complete:true};await fs.writeFile(new URL('../../docs/assignments/evidence/3a-real-rag.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');console.log('6段完整条款、512维单位向量、中文语义改写检索与无关问题拒答通过。');
