import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const task=await taskSpace(Number(process.env.EGO_TASK_SPACE||11));const page=task.page('p1');const cases=[];
async function perform(action,selector,value){try{return await page[action](selector,value);}catch(error){if(!/viewport|visible|offscreen/i.test(String(error)))throw error;await page.evaluate(sel=>document.querySelector(sel.split(' >> ')[0]).scrollIntoView({block:'center'}),selector);return await page[action](selector,value);}}
await page.goto('http://127.0.0.1:5173/guide');await page.waitForSelector('#guide-input',{timeout:20000});console.log(await page.snapshot());
const initial=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,disabled:document.querySelector('button[aria-label="发送购书问题"]').disabled,nav:document.querySelector('a[href="/guide"]').getAttribute('aria-current')}));assert.equal(initial.overflow,false);assert.equal(initial.disabled,true);assert.equal(initial.nav,'page');cases.push({case:'welcome',...initial});
await page.cdp('Network.enable');
try{await page.cdp('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1});for(const q of ['推荐一本学习微服务的书，拆了塑封不喜欢还能退吗？','会员积分有效期多久？']){await perform('fill','#guide-input',q);await perform('press','#guide-input','Enter');await page.waitForFunction(()=>!document.querySelector('#guide-input').disabled,undefined,{timeout:10000});}const errors=await page.evaluate(()=>[...document.querySelectorAll('.assistant-error')].map(e=>e.textContent));assert.equal(errors.length,2);assert.ok(errors.every(e=>e.includes('连接暂时中断')));cases.push({case:'two-offline-errors',errors});}
finally{await page.cdp('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});}
await perform('click','.assistant-error button >> nth=0');await page.waitForSelector('.guide-book-results',{timeout:240000});await page.waitForSelector('.guide-sources',{timeout:20000});
const final=await page.evaluate(()=>({questions:[...document.querySelectorAll('.assistant-question')].map(e=>e.textContent),earlierReplied:!!document.querySelectorAll('.guide-turn')[0].querySelector('.guide-answer-text'),laterError:document.querySelectorAll('.guide-turn')[1].querySelector('.assistant-error')?.textContent,answer:document.querySelector('.guide-answer-text').textContent,books:[...document.querySelectorAll('.guide-book-results strong')].map(e=>e.textContent),inputDisabled:document.querySelector('#guide-input').disabled,composerHeight:document.querySelector('.assistant-composer').getBoundingClientRect().height,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(final.questions.length,2);assert.equal(final.earlierReplied,true);assert.match(final.laterError,/连接暂时中断/);assert.equal(final.questions[1],'会员积分有效期多久？');assert.equal(final.inputDisabled,false);assert.equal(final.overflow,false);assert.match(final.answer,/policy-2/);assert.ok(final.books.some(t=>t.includes('微服务')));cases.push({case:'retry-earlier-complex-preserves-later',...final});
await perform('click','.guide-sources summary');await page.evaluate(()=>document.querySelector('.guide-trace').scrollIntoView({block:'center'}));await perform('click','.guide-trace summary');const trace=await page.evaluate(()=>({steps:document.querySelectorAll('.guide-trace li').length,text:document.querySelector('.guide-trace').textContent,source:document.querySelector('.guide-sources').textContent}));assert.ok(trace.steps>=2);for(const label of ['Thought','Action','Observation','search_book_catalog','query_store_policy'])assert.ok(trace.text.includes(label));assert.match(trace.source,/不接受非质量原因退货/);cases.push({case:'trace-and-sources',...trace});
await perform('fill','#guide-input','第二行');await perform('press','#guide-input','Shift+Enter');await perform('fill','#guide-input','第一行\n第二行');assert.equal(await page.evaluate(()=>document.querySelectorAll('.assistant-question').length),2);cases.push({case:'multiline-does-not-send',value:await page.evaluate(()=>document.querySelector('#guide-input').value)});await perform('fill','#guide-input','');
await page.evaluate(()=>{document.querySelector('.assistant-messages').scrollTop=0;window.scrollTo(0,200);});
await perform('click','.guide-book-results a');await page.waitForFunction(()=>location.pathname==='/books/building-microservices'&&document.querySelector('h1')?.textContent.includes('微服务'),undefined,{timeout:20000});cases.push({case:'recommended-book-detail',url:await page.evaluate(()=>location.href)});
await page.goto('http://127.0.0.1:5173/guide');await page.waitForSelector('#guide-input',{timeout:20000});await perform('fill','#guide-input','你好');await perform('press','#guide-input','Enter');await page.waitForSelector('.guide-answer-text',{timeout:120000});await perform('click','.assistant-chat-header button');const reset=await page.evaluate(()=>({questions:document.querySelectorAll('.assistant-question').length,welcome:!!document.querySelector('.assistant-welcome'),value:document.querySelector('#guide-input').value}));assert.equal(reset.questions,0);assert.equal(reset.welcome,true);assert.equal(reset.value,'');cases.push({case:'new-conversation',...reset});await page.evaluate(()=>window.scrollTo(0,0));
await fs.writeFile(new URL('../../docs/assignments/evidence/3b-browser.json',import.meta.url),JSON.stringify({testedAt:new Date().toISOString(),cases,functionalComplete:true,visualReview:{complete:false},complete:false},null,2)+'\n');console.log('购书向导默认态、断网、单问题重试、复合回复、依据和完整行动记录、输入行为通过。');
